Repository Tybot204/wswp, pull requests merged in 2024-09, with the labels that each got.

#1 Basic database setup and default game interactions
  eslint.config.mjs
  package.json
  prisma/migrations/20240907001008_add_games/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  src/commands/addGame.ts
  src/commands/listGames.ts
  src/index.ts
  yarn.lock
Labels: enhancement

#2 Add Discord user to game when created
  prisma/migrations/20240907010447_add_created_by_to_games/migration.sql
  prisma/schema.prisma
  src/commands/addGame.ts
  src/index.ts
  src/util/registerUser.ts
Labels: enhancement

#3 Reorganize commands to be easier to extend and add
  src/commands/addGame.ts
  src/commands/index.ts
  src/commands/listGames.ts
  src/index.ts
  src/util/registerUser.ts
Labels: enhancement

#4 Add basic rating system for games
  prisma/migrations/20240907020259_add_ratings/migration.sql
  prisma/schema.prisma
  src/commands/index.ts
  src/commands/rateGames.ts
Labels: enhancement

#5 Handle rateGames timeouts due to inactivity
  src/commands/rateGames.ts
Labels: bug

#6 Enhance button colors when using rateGames
  src/commands/rateGames.ts
Labels: enhancement

#7 Fix sort imports linting rule not working
  eslint.config.mjs
  src/index.ts
  webpack.config.ts
Labels: bug

#8 Add basic whatShouldWePlay command to determine best ratings for given players
  eslint.config.mjs
  src/commands/index.ts
  src/commands/whatShouldWePlay.ts
Labels: enhancement

#9 Add project README with setup steps
  .github/CODEOWNERS
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
Labels: documentation

#10 Add basic Steam integration when adding and requesting games
  package.json
  prisma/migrations/20240908022732_add_images_and_url_to_games/migration.sql
  prisma/schema.prisma
  src/commands/addGame.ts
  src/commands/whatShouldWePlay.ts
  src/index.ts
  yarn.lock
Labels: enhancement

#11 Format embed for whatShouldWePlay command per design
  src/commands/whatShouldWePlay.ts
Labels: enhancement

#12 Add game description from Steam when available
  prisma/migrations/20240908042157_add_description_to_games/migration.sql
  prisma/schema.prisma
  src/commands/addGame.ts
  src/commands/whatShouldWePlay.ts
Labels: enhancement

#13 Add client validation to command arguments
  src/commands/addGame.ts
  src/commands/whatShouldWePlay.ts
  src/index.ts
Labels: enhancement

#14 Update rateGames responses to include full game details
  src/commands/rateGames.ts
Labels: enhancement

#15 Remove discordName from users as it is unused
  prisma/migrations/20240908051833_remove_discord_name_from_users/migration.sql
  prisma/schema.prisma
  src/util/registerUser.ts
Labels: task

#16 Add guildId to games to separate servers
  prisma/migrations/20240908071437_add_guild_id_to_games/migration.sql
  prisma/schema.prisma
  src/commands/addGame.ts
  src/commands/listGames.ts
  src/commands/rateGames.ts
Labels: enhancement, migration

#17 Add all option to re-rate all games
  src/commands/rateGames.ts
Labels: enhancement

#18 Add removeGame command using autocomplete
  prisma/migrations/20240908081538_add_on_delete_cascade_to_ratings/migration.sql
  prisma/schema.prisma
  src/commands/index.ts
  src/commands/removeGame.ts
  src/index.ts
Labels: enhancement, migration

#19 Add release status to games
  prisma/schema.prisma
  src/commands/addGame.ts
  src/commands/whatShouldWePlay.ts
  src/index.ts
Labels: enhancement

#20 Add development environment script
  package.json
  webpack.config.ts
  yarn.lock
Labels: task

#22 New rate single game command for rating or re-rating individual games.
  src/commands/index.ts
  src/commands/rateSingleGame.ts
Labels: enhancement

#24 Add CircleCI configuration with basic lint and build workflow
  .circleci/config.yml
  README.md
Labels: task
